{% set version = "4.1.1" %}

package:
  name: swig
  version: {{ version }}

source:
  fn: swig-{{ version }}.tar.gz
  url: http://prdownloads.sourceforge.net/swig/swig-{{ version }}.tar.gz
  sha256: 2af08aced8fcd65cdb5cc62426768914bedc735b1c250325203716f78e39ac9b
  patches:
    # fixes -swiglib path
    - swiglib.patch

build:
  number: 0

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make  # [unix]
    - cmake  # [win]
    - winflexbison  # [win]
  host:
    - pcre2

test:
  commands:
    - swig -help
    - swig -swiglib

about:
  home: http://www.swig.org/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: C/C++ parser code generator

extra:
  recipe-maintainers:
    - jakirkham
    - jschueller
    - msarahan
    - ocefpaf
