{% set version = "4.1.0" %}

package:
  name: swig
  version: {{ version }}

source:
  fn: swig-{{ version }}.tar.gz
  url: http://prdownloads.sourceforge.net/swig/swig-{{ version }}.tar.gz
  sha256: d6a9a8094e78f7cfb6f80a73cc271e1fe388c8638ed22668622c2c646df5bb3d
  patches:
    # fixes -swiglib path
    - swiglib.patch

build:
  number: 3

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make  # [unix]
    - cmake  # [win]
    - winflexbison  # [win]
  host:
    - pcre2

test:
  commands:
    - swig -help
    - swig -swiglib

about:
  home: http://www.swig.org/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: C/C++ parser code generator

extra:
  recipe-maintainers:
    - jakirkham
    - jschueller
    - msarahan
    - ocefpaf
