{% set version = "4.0.2" %}

package:
  name: swig
  version: {{ version }}

source:
  fn: swig-{{ version }}.tar.gz  # [unix]
  url: http://prdownloads.sourceforge.net/swig/swig-{{ version }}.tar.gz  # [unix]
  sha256: d53be9730d8d58a16bf0cbd1f8ac0c0c3e1090573168bfa151b01eb47fa906fc  # [unix]
  fn: swigwin-{{ version }}.zip  # [win]
  url: http://prdownloads.sourceforge.net/swig/swigwin-{{ version }}.zip  # [win]
  sha256: daadb32f19fe818cb9b0015243233fc81584844c11a48436385e87c050346559  # [win]
  patches:
    # https://github.com/swig/swig/commit/9c50887daa2b44251e77be8123c63df238034cf5
    - python_3.9_support.patch

build:
  number: 1
  detect_binary_files_with_prefix: true  # [unix]

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('cxx') }}  # [unix]
    - make  # [unix]
  host:
    - pcre  # [unix]
  run:
    - pcre  # [unix]

test:
  commands:
    - swig  -help

about:
  home: http://www.swig.org/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: C/C++ parser code generator

extra:
  recipe-maintainers:
    - jakirkham
    - jschueller
    - msarahan
    - ocefpaf
