appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: KzWo3dEOHSWg43lf602lOd2vJ85CAYfkQMq0bD8orLhDK4LPnytwfQnew+aFN3Bjmr0I2wL0SUVwAgGzfCPVJG9oL3tAUPvtJyXd3zGv1Bjsr7KqT5MRHCxO/y+zCFwvC8nV/VCfVcdcwT9146XDtlC0rsC9PpwMYAMPqPjG4PRq+tILe4Kc7eEliGlwljsUjT2hyD+DYbuxqW4aQOB16yb0BOg39md4QuZFBuPdPo+6jJaCCiH4AnTdBSDv6gAWPifIRb4ssw43vHcK3/Xop6CC0pHi1dWRZMnTIdkF5d/KS0vmxrJ2k07izfDLXDu8XEMMp69n2qFTbInTNnvojyelYEtUU0brDZUDGqGXjnej04/9P8bX8wlpLP7aODZNSW6PFfmcdR1cPvkGgNnk4RJA7y4Icby2A58zMcFvbDFOF9msfIzwgPaKnizBk90hzXbSPeD/mPZ5EB2jBZro8w/4hyLmDU7KYXxqZeHHPp1QwKEo6uMcMfdT+cZzTBKgbJ7LhASw4CCJrxzykiR664C8XlY24G12LSDpemKHpzm73Iutc4h5jIV1vgj5uXm72nnACaQxMnyyaLxs/mgKOasfwlcIXyt1MURJKuRTQzecB0uoG1muJikQn+20B0S5TG73rCy2qTgczq6lz7/5eh7GQAUC1AZzxcMsGZIhaSQ=}
